[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.black]
line-length = 79

[tool.mypy]
mypy_path = "stubs"
strict = true

[tool.pylint.'messages control']
disable = [
    "too-few-public-methods",
    "too-many-instance-attributes",
    "not-callable",        # false positive for Beancount Entries
    "wrong-import-order",
    "isinstance-second-argument-not-valid-type"
]

[tool.pylint.design]
# max args for a function / method
max-args = 7

[tool.pylint.similarities]
ignore-imports = true

[tool.ruff]
target-version = "py37"
extend-select = [
    "B",
    "D",
    "C4",
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    "Q",
    "RUF",
    "TID",
    "UP",
    "W",
    "YTT",
]
extend-ignore = [
    "D102",  # allow undocumented methods
    "D105",  # allow magic methods to be undocumented
    "D107",  # allow __init__ to be undocumented - the class should be.
    # Copied from ruff's readme for "Google style" docstrings:
    "D203",
    "D212",
    "D213",
    "D214",
    "D215",
    "D404",
    "D405",
    "D406",
    "D407",
    "D408",
    "D409",
    "D410",
    "D411",
    "D413",
    "D415",
    "D416",
    "D417",
    "PLR2004",  # allow magic constants in comparisons
]

[tool.ruff.per-file-ignores]
"contrib/**" = ["D"]
"docs/**" = ["D"]
"tests/**" = ["D"]
"stubs/**" = ["D"]
"src/fava/core/filters.py" = ["D"]
